apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ow8s3fa7s-python 
  janus-idp.io/tekton: ow8s3fa7s-python
  backstage.io/kubernetes-id: ow8s3fa7s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ow8s3fa7s-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  