apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ow8s3fa7s-python-gitops
  description: This is GitOps manifest for ow8s3fa7s-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ow8s3fa7s-python
    janus-idp.io/tekton: ow8s3fa7s-python 
    backstage.io/kubernetes-id: ow8s3fa7s-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ow8s3fa7s-python
